// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PolicyUIClient is the client API for PolicyUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyUIClient interface {
	// ListEngineSpecs returns a list of Policy Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (PolicyUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type policyUIClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyUIClient(cc grpc.ClientConnInterface) PolicyUIClient {
	return &policyUIClient{cc}
}

func (c *policyUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (PolicyUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PolicyUI_ServiceDesc.Streams[0], "/v1.PolicyUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &policyUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PolicyUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type policyUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *policyUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *policyUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.PolicyUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyUIServer is the server API for PolicyUI service.
// All implementations must embed UnimplementedPolicyUIServer
// for forward compatibility
type PolicyUIServer interface {
	// ListEngineSpecs returns a list of Policy Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, PolicyUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedPolicyUIServer()
}

// UnimplementedPolicyUIServer must be embedded to have forward compatible implementations.
type UnimplementedPolicyUIServer struct {
}

func (UnimplementedPolicyUIServer) ListEngineSpecs(*ListEngineSpecsRequest, PolicyUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedPolicyUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedPolicyUIServer) mustEmbedUnimplementedPolicyUIServer() {}

// UnsafePolicyUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyUIServer will
// result in compilation errors.
type UnsafePolicyUIServer interface {
	mustEmbedUnimplementedPolicyUIServer()
}

func RegisterPolicyUIServer(s grpc.ServiceRegistrar, srv PolicyUIServer) {
	s.RegisterService(&PolicyUI_ServiceDesc, srv)
}

func _PolicyUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PolicyUIServer).ListEngineSpecs(m, &policyUIListEngineSpecsServer{stream})
}

type PolicyUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type policyUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *policyUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PolicyUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PolicyUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyUI_ServiceDesc is the grpc.ServiceDesc for PolicyUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PolicyUI",
	HandlerType: (*PolicyUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _PolicyUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _PolicyUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "policy-ui.proto",
}
